version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always
  api:
    container_name: kyahaal-backend
    image: devaryakjha/kyahaal-backend:latest
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: yarn start:prod
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
